-- Staging table for cleaned dataset (loaded from DB-ready CSV)
DROP TABLE IF EXISTS fifa.stg_players_clean;

CREATE TABLE fifa.stg_players_clean (
  player_key TEXT,
  full_name TEXT,
  birth_date DATE,
  age NUMERIC,
  height_cm NUMERIC,
  weight_kgs NUMERIC,
  preferred_foot TEXT,
  body_type TEXT,
  nationality TEXT,
  national_team TEXT,

  positions TEXT,
  primary_position TEXT,
  positions_count NUMERIC,

  overall_rating NUMERIC,
  potential NUMERIC,
  value_euro NUMERIC,
  wage_euro NUMERIC,
  release_clause_euro NUMERIC,

  crossing NUMERIC,
  finishing NUMERIC,
  heading_accuracy NUMERIC,
  short_passing NUMERIC,
  volleys NUMERIC,
  dribbling NUMERIC,
  curve NUMERIC,
  freekick_accuracy NUMERIC,
  long_passing NUMERIC,
  ball_control NUMERIC,
  acceleration NUMERIC,
  sprint_speed NUMERIC,
  agility NUMERIC,
  reactions NUMERIC,
  balance NUMERIC,
  shot_power NUMERIC,
  jumping NUMERIC,
  stamina NUMERIC,
  strength NUMERIC,
  long_shots NUMERIC,
  aggression NUMERIC,
  interceptions NUMERIC,
  positioning NUMERIC,
  vision NUMERIC,
  penalties NUMERIC,
  composure NUMERIC,
  marking NUMERIC,
  standing_tackle NUMERIC,
  sliding_tackle NUMERIC,

  flag_missing_birth_date BOOLEAN,
  flag_overall_gt_potential BOOLEAN,
  flag_non_positive_value BOOLEAN,
  flag_non_positive_wage BOOLEAN
);
